import { Geist, Geist_Mono } from "next/font/google";
import { CartProvider } from "@/CartContext";

import "./globals.css";
import { WishlistProvider } from "@/WishlistContext";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "e-commerce app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider>
          <WishlistProvider>
          <Navbar />
          {children}
          <Footer />
        </WishlistProvider>
        </CartProvider>
      </body>
    </html>
  );
}
