import { Geist, Geist_Mono } from "next/font/google";
import { CartProvider } from "@/CartContext";
import NextTopLoader from 'nextjs-toploader';
import "./globals.css";
import { WishlistProvider } from "@/WishlistContext";
import Footer from "@/components/Footer";
import Navbar from "@/components/header/Navbar";
import { ProductsProvider } from "@/ProductsContext";
import BelowHeader from "@/components/header/belowHeader";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "e-commerce app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider>
          <WishlistProvider>
            <ProductsProvider>
              <NextTopLoader />
              <Toaster position="top-center" />
              <Navbar />
              {/* <BelowHeader /> */}
              {children}
              <Footer />
            </ProductsProvider>
          </WishlistProvider>
        </CartProvider>
      </body>
    </html>
  );
}
